name: NestJS CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install
        working-directory: ./NEST_JS # Use the correct directory name

      - name: Build Nest.js App
        run: npm run build
        working-directory: ./NEST_JS # Use the correct directory name

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

    # Add additional steps for testing or other checks

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region # Replace with your AWS region

      # Add steps for deploying to AWS or storing data in AWS services
