name: Build and Deploy

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

      - name: Run NestJS application
        run: npm run start &
        shell: bash

      - name: Wait for the application to start
        run: sleep 20

  deploy:
    runs-on: windows-latest

    needs: build

    steps:
      - name: Debug - List artifacts
        run: ls -R

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Debug - List downloaded artifacts
        run: ls -R

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "Asia Pacific (Singapore) ap-southeast-1"

      - name: Upload to S3
        run: aws s3 cp dist s3://${{ secrets.AWS_BUCKET }}/ --recursive
