name: CI/CD Pipeline

on:
  push:
    tags:
      - '**'  # Trigger only on tag pushes

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install pkg globally
      run: npm install -g pkg

    - name: Build
      run: npm run build

    - name: Generate Binary
      run: npm run package

    - name: Configure AWS CLI and Upload Binary
      shell: bash
      run: |
        # Configure AWS CLI
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region 'ap-southeast-1'
    
        # Extract tag name
        TAG_NAME=$(echo ${GITHUB_REF##*/})
        echo "Extracted tag name: $TAG_NAME"
    
        # Upload the binary to Amazon S3
        aws s3 cp ./dist/my-app.exe s3://${{ secrets.AWS_BUCKET }}/$TAG_NAME/back_end/my-app.exe --acl public-read
